config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
  	get "signin" => 'devise/sessions#new'
  	delete "signout" => 'devise/sessions#destroy'
  	get "signup" => 'devise/registrations#new'
  end
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact_us' => 'pages#contact_us'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Test Navbar -->

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="#">One Month Rails</a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li><%= link_to "Home", root_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Contact", contact_us_path, class: "nav-link" %></li>
            </ul>  
          </div>
                <% if user_signed_in? %>
                  <%= link_to "Sign Out", signout_path, method: :delete, class: "nav-link" %>
                <% else %>
                  <%= link_to "Sign In", signin_path, class: "nav-link" %>
                  <%= link_to "New User", signup_path, class: "nav-link btn btn-primary" %>
                <% end %>

        </div>
    </nav>

    <!-- Flash messages -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
      <% end %>

    <!--  <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    -->

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/contact_us.html.erb
<h1>Contact Us</h1>
<p>This is how you contact us.<br>
If you'd like to email me, you can do so at <a href="mailto:duncanscarry@gmail.com">Duncan Scarry's email address.</a>
</p>
<p>If you want to contact me, call (239) 398-1251</p>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-home">
    <div class="container">
        <% if user_signed_in? %>
            <h1> Welcome Back</h1>
        <% else %>
            <h1>Welcome to my website!</h1>
        <% end %>

        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %> 
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>